name: roomore_hotels_test
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  google_fonts: ^6.3.1
  easy_localization: ^3.0.8
  shared_preferences: ^2.5.3
  qr_code_scanner_plus: ^2.0.10+1
  permission_handler: ^12.0.1
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  google_sign_in: ^7.1.1
  sign_in_with_apple: ^7.0.1
  cloud_firestore: ^6.0.1
  equatable: ^2.0.7
  http: ^1.5.0
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/RooMoreLogo.png
    - assets/images/RooMoreGrayLogo.png
    - assets/translations/ar.json
    - assets/translations/en.json