// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9vDeP1fH6WHfMjduI_S_zYOggP98bkVg',
    appId: '1:236361081790:web:af77fab9c8531675614fef',
    messagingSenderId: '236361081790',
    projectId: 'roomoretest',
    authDomain: 'roomoretest.firebaseapp.com',
    databaseURL: 'https://roomoretest-default-rtdb.firebaseio.com',
    storageBucket: 'roomoretest.firebasestorage.app',
    measurementId: 'G-YGW74CW74X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdhqjHduVVIXOFCA2HS9HYisoSWunDDeQ',
    appId: '1:236361081790:android:e2b7e1e61609fc50614fef',
    messagingSenderId: '236361081790',
    projectId: 'roomoretest',
    databaseURL: 'https://roomoretest-default-rtdb.firebaseio.com',
    storageBucket: 'roomoretest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw1Ayx3gVXtfIOgF2MdERgWZ8rAIFTojM',
    appId: '1:236361081790:ios:7c31b4c0f64f5715614fef',
    messagingSenderId: '236361081790',
    projectId: 'roomoretest',
    databaseURL: 'https://roomoretest-default-rtdb.firebaseio.com',
    storageBucket: 'roomoretest.firebasestorage.app',
    androidClientId: '236361081790-b2ugdr9pjtdki2am6p54p5rp1jvi78jg.apps.googleusercontent.com',
    iosClientId: '236361081790-8v72oak1iqo9e75jdg9lms7nb64t6tkc.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomoreHotelsTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw1Ayx3gVXtfIOgF2MdERgWZ8rAIFTojM',
    appId: '1:236361081790:ios:7c31b4c0f64f5715614fef',
    messagingSenderId: '236361081790',
    projectId: 'roomoretest',
    databaseURL: 'https://roomoretest-default-rtdb.firebaseio.com',
    storageBucket: 'roomoretest.firebasestorage.app',
    androidClientId: '236361081790-b2ugdr9pjtdki2am6p54p5rp1jvi78jg.apps.googleusercontent.com',
    iosClientId: '236361081790-8v72oak1iqo9e75jdg9lms7nb64t6tkc.apps.googleusercontent.com',
    iosBundleId: 'com.example.roomoreHotelsTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9vDeP1fH6WHfMjduI_S_zYOggP98bkVg',
    appId: '1:236361081790:web:15511655473dc663614fef',
    messagingSenderId: '236361081790',
    projectId: 'roomoretest',
    authDomain: 'roomoretest.firebaseapp.com',
    databaseURL: 'https://roomoretest-default-rtdb.firebaseio.com',
    storageBucket: 'roomoretest.firebasestorage.app',
    measurementId: 'G-83C3PCQF2T',
  );
}
