// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9vDeP1fH6WHfMjduI_S_zYOggP98bkVg',
    appId: '1:236361081790:web:af77fab9c8531675614fef',
    messagingSenderId: '236361081790',
    projectId: 'roomoretest',
    authDomain: 'roomoretest.firebaseapp.com',
    storageBucket: 'roomoretest.firebasestorage.app',
    measurementId: 'G-YGW74CW74X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdhqjHduVVIXOFCA2HS9HYisoSWunDDeQ',
    appId: '1:236361081790:android:60b4c4ba0d2f729e614fef',
    messagingSenderId: '236361081790',
    projectId: 'roomoretest',
    storageBucket: 'roomoretest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw1Ayx3gVXtfIOgF2MdERgWZ8rAIFTojM',
    appId: '1:236361081790:ios:2d32196a33a5ae6f614fef',
    messagingSenderId: '236361081790',
    projectId: 'roomoretest',
    storageBucket: 'roomoretest.firebasestorage.app',
    iosBundleId: 'com.example.roomoreTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw1Ayx3gVXtfIOgF2MdERgWZ8rAIFTojM',
    appId: '1:236361081790:ios:2d32196a33a5ae6f614fef',
    messagingSenderId: '236361081790',
    projectId: 'roomoretest',
    storageBucket: 'roomoretest.firebasestorage.app',
    iosBundleId: 'com.example.roomoreTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9vDeP1fH6WHfMjduI_S_zYOggP98bkVg',
    appId: '1:236361081790:web:f5bd529ff619e057614fef',
    messagingSenderId: '236361081790',
    projectId: 'roomoretest',
    authDomain: 'roomoretest.firebaseapp.com',
    storageBucket: 'roomoretest.firebasestorage.app',
    measurementId: 'G-MRJT8NQ84M',
  );
}
